# Generated by Django 2.1.15 on 2022-05-10 07:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import localflavor.in_.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(help_text='Full name', max_length=512)),
                ('address_first_line', models.CharField(help_text='Flat, House no., Building, Company, Apartment', max_length=512)),
                ('address_second_line', models.CharField(blank=True, help_text='Area, Street, Sector, Village', max_length=512, null=True)),
                ('landmark', models.CharField(blank=True, help_text='Landmark', max_length=512, null=True)),
                ('pincode', models.IntegerField(help_text='Pin code')),
                ('town_or_city', models.CharField(blank=True, help_text='Town or City', max_length=512, null=True)),
                ('state', localflavor.in_.models.INStateField(help_text='State', max_length=2)),
                ('address_type', models.CharField(choices=[('home', 'Home'), ('work', 'Office/Commercial')], default='home', max_length=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
